/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class OSADictionaryControllerPrivate, OSADictionaryView;

@interface OSADictionaryController : NSController
{
    OSADictionaryView *dictionaryView;
    NSSearchField *searchField;
    OSADictionaryControllerPrivate *_private;
}

- (void)awakeFromNib;
- (id)init;
- (id)initWithDictionary:(id)fp8;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)dictionary;
- (void)setDictionary:(id)fp8;
- (id)dictionaryView;
- (void)setDictionaryView:(id)fp8;
- (id)searchField;
- (void)setSearchField:(id)fp8;

@end

