/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "OSASplitView.h"

@class OSADictionaryViewPrivate, WebView;

@interface OSADictionaryView : OSASplitView
{
    OSASplitView *_splitView;
    NSOutlineView *_outlineView;
    WebView *_contentView;
    NSTabView *_tabView;
    NSTableView *_tableView;
    NSBrowser *_suiteBrowser;
    NSBrowser *_containmentBrowser;
    NSBrowser *_inheritanceBrowser;
    int _viewMode;
    BOOL _searching;
    OSADictionaryViewPrivate *_private;
}

- (void)awakeFromNib;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)dealloc;
- (id)splitView;
- (void)setSplitView:(id)fp8;
- (id)outlineView;
- (void)setOutlineView:(id)fp8;
- (id)contentView;
- (void)setContentView:(id)fp8;
- (id)tabView;
- (void)setTabView:(id)fp8;
- (id)tableView;
- (void)setTableView:(id)fp8;
- (id)suiteBrowser;
- (void)setSuiteBrowser:(id)fp8;
- (id)containmentBrowser;
- (void)setContainmentBrowser:(id)fp8;
- (id)inheritanceBrowser;
- (void)setInheritanceBrowser:(id)fp8;
- (int)viewMode;
- (void)setViewMode:(int)fp8;

@end

