/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <OSAKit/OSADictionaryController.h>

@interface OSADictionaryController (OSAPrivate)
- (id)dataSource;
- (void)setDataSource:(id)fp8;
- (id)definitionsController;
- (void)setDefinitionsController:(id)fp8;
- (id)dictionaryHistory;
- (void)setDictionaryHistory:(id)fp8;
- (BOOL)selectingObjects;
- (void)setSelectingObjects:(BOOL)fp8;
- (void)updateContentView;
- (void)selectDefinitionsInContentView:(id)fp8;
- (id)makeDataSourceFromDictionary:(id)fp8;
- (id)dataSourceItemWithDefinition:(id)fp8 inItems:(id)fp12;
- (id)dataSourceItemWithDefinition:(id)fp8;
- (id)definitionForAnchor:(id)fp8 inItems:(id)fp12;
- (id)definitionForAnchor:(id)fp8;
- (id)parentItemOfDataSourceItem:(id)fp8 inItems:(id)fp12;
- (id)parentItemOfDataSourceItem:(id)fp8;
- (id)itemsToExpandForItem:(id)fp8;
- (void)expandOutlineItemsForObjects:(id)fp8;
- (void)selectOutlineItemsForObjects:(id)fp8;
- (id)viewState;
- (void)setViewState:(id)fp8;
- (BOOL)canGoBack;
- (BOOL)canGoForward;
- (void)changeSelection:(id)fp8;
- (void)makeTextSmaller:(id)fp8;
- (void)makeTextLarger:(id)fp8;
- (void)goBack:(id)fp8;
- (void)goForward:(id)fp8;
- (id)selectedDefinitions;
- (void)webView:(id)fp8 decidePolicyForNavigationAction:(id)fp12 request:(id)fp16 frame:(id)fp20 decisionListener:(id)fp24;
@end

