/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface OSASplitView : NSSplitView
{
    BOOL _collapsed;
    float _originalPosition;
    float _minimumPosition;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (BOOL)collapsed;
- (void)setCollapsed:(BOOL)fp8;
- (float)originalPosition;
- (void)setOriginalPosition:(float)fp8;
- (float)minimumPosition;
- (void)setMinimumPosition:(float)fp8;
- (void)mouseDown:(id)fp8;

@end

